---
# This playbook says hi and includes pb01,pb02
- name: this is a play at the top level of a file
  hosts: all
  remote_user: root
  tasks:
  - name: say hi
    tags: foo
    shell: echo "hi..."

- include: pb01.yml
- include: pb02.yml
